# Tensor

In [1]:
import torch
import numpy as np

## Initializing a Tensor

### Directly from 

Tensors can be created directly from data. **The data type is automatically inferred.**

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
data = ((1,2), (3,4))
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

### From a NumPy array

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

### From another tensor

In [ ]:
#The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data,dtype=torch.float32)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.9410, 0.8643],
        [0.9783, 0.2960]])


## Atrributes of a Tensor

Tensor attribute:
- shape
- dtype
- device

In [11]:
print(f"shape: {x_rand.shape}")
print(f"dtype: {x_rand.dtype}")
print(f"device: {x_rand.device}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
# x_rand.to(device)
x_rand = x_rand.to(device)

# 为什么上面的代码是错的？因为.to()方法不会原地修改tensor

print(f"device: {x_rand.device}")

shape: torch.Size([2, 2])
dtype: torch.float32
device: cuda:0
cuda
device: cuda:0


In [8]:
torch.cuda.is_available()

True

## Operations on Tensors

Each of these operations can be run on the CPU and Accelerator such as CUDA

By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using .to method (after checking for accelerator availability).**Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!** 

In [13]:
# We move our tensor to the current accelerator if available

tensor = torch.rand(2,3)

if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

print(tensor.device)

cuda:0


### Standard numpy-like indexing and slicing:

In [15]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[:,-1]}")
tensor[:, -1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


### Joining tensors 

In [16]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])


### Arithmetic operations

In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

### Single-element tensors

If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [18]:
print(tensor)
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor(12.)
12.0


### In-place operations (原地操作)

Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [19]:
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

tensor([[6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.]])
